# Generated by Django 3.2.6 on 2021-08-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('in_stock_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('gallon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('five_gallon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('custom', models.BooleanField(blank=True)),
            ],
            bases=('inventory.product',),
        ),
    ]
